### PR TITLE
Amended packages

### PR DESCRIPTION
**Pull request by sergeyklay**
Added:
- PostgreSQL
- SQLite
- php5-gd
- php5-imagick
- php5-sqlite

### CODE REVIEW

**Comment by JREAM** [comment]
**Testing On**
- Vagrant 1.7.2
- VirtualBox 4.3.20r96996
- Host: Ubutnu 15 Vivid Vervit

**Comment by sergeyklay** [comment]
@JREAM PostgreSQL 9.4 not available for non-LTS Ubuntu, e.g. 15

**Comment by JREAM** [comment]
This is working, however I have one problem that might be related to this push:

```
vagrant@phalcon-vm:/var/www$ cd /vagrant/www
vagrant@phalcon-vm:/vagrant/www$ phalcon project superstar

Phalcon DevTools (2.0.7)

PHP Warning:  mkdir(): Permission denied in /opt/phalcon-tools/scripts/Phalcon/Builder/Project.php on line 109
PHP Stack trace:
PHP   1. {main}() /opt/phalcon-tools/phalcon.php:0
PHP   2. Phalcon\Script->run() /opt/phalcon-tools/phalcon.php:83
PHP   3. Phalcon\Script->dispatch() /opt/phalcon-tools/scripts/Phalcon/Script.php:146
PHP   4. Phalcon\Commands\Builtin\Project->run() /opt/phalcon-tools/scripts/Phalcon/Script.php:121
PHP   5. Phalcon\Builder\Project->build() /opt/phalcon-tools/scripts/Phalcon/Commands/Builtin/Project.php:73
PHP   6. mkdir() /opt/phalcon-tools/scripts/Phalcon/Builder/Project.php:109
                                                                  
  Error: Unable create project directory /vagrant/www/superstar/  
                                                                  
```

**Comment by JREAM** [comment]
@sergeyklay I am installing in Ubuntu 15 the host, but still running `config.vm.box = "ubuntu/trusty64"` -- The message I receive is (Seems OK for the Guest):
```
==> default: A newer version of the box 'ubuntu/trusty64' is available! You currently
==> default: have version '14.04'. The latest is version '20150924.0.0'. Run
==> default: `vagrant box update` to update.
```

**Comment by sergeyklay** [comment]
> Phalcon DevTools (2.0.7)

Latest Phalcon is 2.0.8

> Error: Unable create project directory /vagrant/www/superstar/

See Vagrantfile
```ruby
config.vm.synced_folder "./www", "/vagrant/www/", :mount_options => [ "dmode=775", "fmode=644" ], :owner => 'www-data', :group => 'www-data'
```

**Comment by sergeyklay** [comment]
Possible need to add `vagrant` user to the `www-data` group

**Comment by JREAM** [comment]
Argh, I'm so used to going into `/var/www` haha. But the creation works with errors.

I wonder why It installs 2.0.7 with `dev-master` for the developer tools. 
`sudo phalcon project superstar` OK

I tried adding manually (This should probably go into the init.sh):
```usermod -a -G www-data vagrant
sudo chown -R :www-data /vagrant/www
sudo chmod -R g+w /vagrant/www
```

Then Change to this:
```config.vm.synced_folder "./www", "/vagrant/www/", :mount_options => [ "dmode=775", "fmode=644" ], :owner => 'vagrant, :group => 'www-data'
```

This will allow us to create projects with the phalcon dev-tools with `vagrant:www-data` and we can happily edit files inside of vagrant if we have to :)

Please let me know if you think that's a good/bad idea!

**Comment by sergeyklay** [comment]
Can you please test non-cli mode with this changes?
For example, would it be possible to create a file (log, cache file, etc.) when the page is refreshed?

**Comment by JREAM** [comment]
Good idea!

- Made a fake project
- Edit the `public/index.php `
- added `<?php a`
- Received:

```( ! ) Parse error: syntax error, unexpected 'throw' (T_THROW) in /vagrant/www/superstar2/public/index.php on line 4```

Looks like the `project-logs` aren't being created (if they are, it's not in `/vagrant/www`)

**Comment by sergeyklay** [comment]
Are you sure that in case of exception will create a file in `/vagrant/www`? I don't remember

**Comment by JREAM** [comment]
We are missing this in the Apache conf, then it works:
```
  ErrorLog  /var/www/projects-error.log
  CustomLog /var/www/projects-access.log combined
```

Just tested quickly by adding:
```
<VirtualHost *:80>
        DocumentRoot /vagrant/www
  ErrorLog  /vagrant/www/project-error.log
  CustomLog /vagrant/www/project-access.log combined
</VirtualHost>
```

**Comment by sergeyklay** [comment]
Added logs

**Comment by JREAM** [comment]
Nice, want me to add the vagrant to www-data group and change the Vagrantfile owner to `vagrant` after merge?

**Comment by sergeyklay** [comment]
Yes, please

**Pull request merged**
